CREATE TABLE `sap-cost-center`
(
    `ControllingArea`       varchar(4) DEFAULT NULL,
    `CostCenter`            varchar(10) DEFAULT NULL,
    `CostCenter_desc`       varchar(40) DEFAULT NULL,
    `ValidityEndDate`       date DEFAULT NULL,
    `ValidityStartDate`     date DEFAULT NULL,
    `CompanyCode`           varchar(4) DEFAULT NULL,
    `BusinessArea`          varchar(4) DEFAULT NULL,
    `CostCtrResponsiblePersonName` varchar(20) DEFAULT NULL,
    `CostCtrResponsibleUser` varchar(12) DEFAULT NULL,
    `CostCenterCurrency`    varchar(5) DEFAULT NULL,
    `ProfitCenter`          varchar(10) DEFAULT NULL,
    `Department`            varchar(12) DEFAULT NULL,
    `FunctionalArea`        varchar(16) DEFAULT NULL,
    `CostCenterStandardHierArea` varchar(12) DEFAULT NULL,
    `CostCenterCategory`    varchar(1) DEFAULT NULL,
    `IsBlkdForPrimaryCostsPosting` tinyint(1) DEFAULT NULL,
    `IsBlkdForSecondaryCostsPosting` tinyint(1) DEFAULT NULL,
    `IsBlockedForRevenuePosting` tinyint(1) DEFAULT NULL,
    `IsBlockedForCommitmentPosting` tinyint(1) DEFAULT NULL,
    `IsBlockedForPlanPrimaryCosts` tinyint(1) DEFAULT NULL,
    `IsBlockedForPlanSecondaryCosts` tinyint(1) DEFAULT NULL,
    `IsBlockedForPlanRevenues` tinyint(1) DEFAULT NULL,
    `ConsumptionQtyIsRecorded` tinyint(1) DEFAULT NULL,
    `CostCenterCreationDate` date DEFAULT NULL,
    PRIMARY KEY (`ControllingArea`, `CostCenter`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
